export { default as IconNotebook } from './IconNotebook.vue'
export { default as IconHome } from './IconHome.vue'
export { default as IconDocument } from './IconDocument.vue'
export { default as IconMagic } from './IconMagic.vue'
export { default as IconTrend } from './IconTrend.vue'
export { default as IconUser } from './IconUser.vue'
export { default as IconEdit } from './IconEdit.vue'
export { default as IconUpload } from './IconUpload.vue'
export { default as IconSearch } from './IconSearch.vue'
export { default as IconPlus } from './IconPlus.vue'
export { default as IconClock } from './IconClock.vue'
export { default as IconLogout } from './IconLogout.vue'
export { default as IconAI} from './IconAI.vue'
export { default as AppLogo} from  './AppLogo.vue'
export { default as IconMindmap } from './IconMindmap.vue'
export { default as IconTranslate } from './IconTranslate.vue'
export { default as IconGitHub } from './IconGitHub.vue'